### PR TITLE
Only copy files when not present

### PR DESCRIPTION
**Pull request by nuFaqtz**

### CODE REVIEW

**Comment by burningice2866** [comment]
@nuFaqtz Looks like https://github.com/nuFaqtz/C1-CMS/commit/bb482ff034f06e166bf5673e39e57774208e8ad7 shouldn't be a part of this Pull request.

**Comment by burningice2866** [comment]
@nuFaqtz Won't "only copying files that doesn't already exists" make problems when ie. upgrading Codemirror? Only way you can do that then is to delete the files under "Composite/lib/codemirror" and re-run "bower install".

I understand the reasoning that if you have a "grunt watch"-task that runs everything on every file change, then its becomes a problem, but i don't see that to be the case. Its only when you do a complete "grunt build" command, that ie. codemirror files are copied, while "grunt watchAll" would be the normal task to run on a day to day basis.

Otherwise the bower-copying task shouldn't be a part of build, so the flow instead would be

grunt copyAll (only do this on first build or when updating components in bower.json)
grunt build
grunt watchAll

**Comment by nuFaqtz** [comment]
@burningice2866 I see your point. In my workflow it made sense - a heavy customized C1- but in general it's like you say. 

nuFaqtz@bb482ff shouldn't be a part of this Pull request indeed - don't know why it's there as I did not put it there. I guess it's because of the 'by compare' creation of the pull.

**Comment by nuFaqtz** [comment]
Will do a new simplified pull

**Comment by burningice2866** [comment]
Pull requests are based on a specific branch, so as long as you keep pushing to that branch, your pull request will be updated.

You should create a branch in your repo specifically for a give feature or fix, and base your pull request on that branch.

**Pull request closed without merging**
